#ifndef ERR_H
#define ERR_H

#define ERR_MSG_TRUNCATED -1
#define ERR_TASK_DOES_NOT_EXIST -2
#define ERR_TASK_NOT_REPLY_BLOCKED -3
#define ERR_NAME_UNREGISTERED -4
#define ERR_NO_OPPONENT -5
#define ERR_INVALID_ARGUMENT -6
#define ERR_INVARIANT_BROKEN -7
#define ERR_HT_FULL -8
#define ERR_HT_NOT_FOUND -9
#define ERR_EVENT_ALREADY_HAS_TASK_WAITING -10
#define ERR_MH_EMPTY -11
#define ERR_MH_FULL -12
#define ERR_NOT_IMPLEMENTED -99;
#endif //ERR_H
